name: CD - Deploy to EKS

on:
  push:
    branches: [ "main" ]
    paths:
      - "k8s/**"
      - ".github/workflows/cd.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # OIDC
      contents: read
    env:
      AWS_REGION: eu-west-2
      CLUSTER_NAME: eks-demo-cluster
      NAMESPACE: demo
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::897545368009:role/gha-eks-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl & kustomize
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          curl -sSL https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_REGION"

      - name: Ensure namespace exists
        run: kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy (Kustomize demo overlay)
        run: kustomize build k8s/overlays/demo | kubectl apply -f -

      - name: Wait for rollout
        run: kubectl rollout status deploy/demo-node-app -n "$NAMESPACE" --timeout=180s
