name: CI - Build & Push to ECR (GitOps bump)

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write        # OIDC to assume AWS role
      contents: read         # read this repo
    env:
      AWS_REGION: eu-west-2
      ECR_REPO: 897545368009.dkr.ecr.eu-west-2.amazonaws.com/eks-demo-app
      GITOPS_REPO: rohanathan/eks-gha-gitops
      GITOPS_FILE: eks-demo-gitops/overlays/demo/kustomization.yaml

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::897545368009:role/gha-eks-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push image (context=app/)
        id: build
        run: |
          IMAGE="${{ env.ECR_REPO }}"
          TAG="${GITHUB_SHA::7}"
          docker build -f app/Dockerfile -t "${IMAGE}:${TAG}" -t "${IMAGE}:latest" app
          docker push "${IMAGE}:${TAG}"
          docker push "${IMAGE}:latest"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"

      # --- GitOps bump via SSH deploy key ---
      - name: Checkout GitOps repo (SSH)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          ssh-key: ${{ secrets.GITOPS_DEPLOY_KEY }}
          path: gitops
          persist-credentials: false

      - name: Update image tag in GitOps kustomization.yaml
        working-directory: gitops
        run: |
          FILE="${GITOPS_FILE}"
          TAG="${{ steps.build.outputs.tag }}"
          # replace the 'newTag:' line under your image
          sed -i -E "s/^\s*newTag:\s*.*/newTag: ${TAG}/" "${FILE}"
          echo "Bumped ${FILE} to tag ${TAG}"
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add "${FILE}"
          git commit -m "GitOps: set eks-demo-app tag to ${TAG}" || echo "No changes to commit"
          git push origin HEAD:main
