name: CI - Build & Push to ECR (no tests/lint)

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # OIDC
      contents: read
    env:
      AWS_REGION: eu-west-2
      ECR_REPO: 897545368009.dkr.ecr.eu-west-2.amazonaws.com/eks-demo-app
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::897545368009:role/gha-eks-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push image (context=app/)
        run: |
          IMAGE=${{ env.ECR_REPO }}
          TAG=${GITHUB_SHA::7}
          docker build -f app/Dockerfile -t $IMAGE:$TAG -t $IMAGE:latest app
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
